### ISSUE TITLE
this project is pretty ass

### ISSUE THREAD

**Issue by m132** [lispfan1987/bizmeme-ng#6]
i care about you though buy CHIA

**Comment by lispfan1987** [comment]
when did i give you permission to post on my project?

**Comment by m132** [comment]
focus on the code wagie we arent paying you for spiteful remarks like that one

**Comment by lispfan1987** [comment]
you have made zero contributions to this project yet you dare talk to me like that?

**Comment by m132** [comment]
i dont care just fix it

**Comment by lispfan1987** [comment]
fix what?

**Comment by m132** [comment]
ur life

**Comment by lispfan1987** [comment]
are you trolling rn?

**Comment by m132** [comment]
listen

**Comment by lispfan1987** [comment]
what?

**Comment by m132** [comment]
listen

**Comment by m132** [comment]
this is a 24/7 business

**Comment by lispfan1987** [comment]
this is a free open source project

**Comment by m132** [comment]
it doesnt even have a proper license how is anybody supposed make big bux on it merely leaving ur name buried in the credits think darmore think

**Comment by lispfan1987** [comment]
stop making me feel bad, you're removed

**Comment by m132** [comment]
☹

**Comment by lispfan1987** [comment]
how do i block people on github?

**Comment by lispfan1987** [comment]
closed for inactivity
